all:
	g++ -std=c++11 Deque_without_macro_MyClass.cpp -o test -ldl -Wall -Wextra -pedantic
	@echo "Compiled file test.o successfully !"

clean:
	rm test
	@echo "Executable file ./test deleted successfully !"